version: '3.8'   # This is the docker-compose format version

services: # This section defines all containers that should run together
  app: # First service - your Quarkus application
    image: quarkus/drivo-jvm    # The image we built earlier with docker build
    ports:
      - "8080:8080"    # Maps port 8080 from container to your computer
    environment: # Environment variables for database connection
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/driving-school
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=1234
    depends_on: # This ensures database starts before the app
      - db

  db: # Second service - PostgreSQL database
    image: postgres:15    # Official PostgreSQL image from Docker Hub
    ports:
      - "5432:5432"     # Maps database port to your computer
    environment: # Database setup variables
      - POSTGRES_DB=driving-school
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234